# site setting
source: src
destination: _site
plugins: plugin
scss:
  source: src/_scss
  destination: 2012/assets/css
js:
  source: src/_js
  destination: 2012/assets/js
  targets:
    lib.js:
      files:
        - lib/jquery.min.js
        - lib/modernizr.js
        - lib/underscore.js 
        - lib/backbone.js
        - lib/davis.js
        - lib/jquery.lazyjaxdavis.js
    script.js:
      files:
        - app/core.js
        - app/utils.js
        - model/avatar.js
        - collection/avatars.js
        - view/avatar.js
        - view/avatarMe.js
        - view/avatarsField.js
        - app/headerNavi.js
        - main.js

# site data
sponsors:

# プラチナスポンサー
#=========================
  - 
    label: Platinum Sponsors
    label_ja: プラチナスポンサー
    icon: ico_01.png
    companies:
      - 
        name: リクルート
        url: http://www.recruit.jp/
        img: recruit.png
        description: |-
          リクルートは、「じゃらん」「SUUMO」「リクナビ」をはじめとする大小様々なWebサービスを展開しています。

          これらのWebサービスを支えるアーキテクチャとして、Solr・Hadoop等オープンソースを積極的に活用しており、現在、リアルタイムWebの実現に向けNode.jsの導入に取り組んでいます。

# ゴールドスポンサー
#=========================
  - 
    label: Gold Sponsors
    label_ja: ゴールドスポンサー
    icon: ico_02.png
    companies:
      - 
        name: DeNA
        url: http://dena.jp/engineer/
        img: dena.png
        description: |-
          ディー・エヌ・エー（DeNA）は、日本、英語圏、中国、韓国へワールドワイドのソーシャルゲームプラットフォーム「Mobage」を展開している、インターネットサービス事業を主軸としたグローバルカンパニーです。

          WW向けコンテンツ展開を支える技術のひとつに、iOS/Androidの両プラットフォーム向けにワンソースでゲームを展開できるクロスプラットフォームゲームエンジン「ngCore」を提供。このプロダクトにおいてNode.jsをはじめとした先鋭的な技術を積極的に活用しています。

      - 
        name: GREE
        url: http://www.gree.co.jp
        img: gree.png
        description: |-
          グリーは、世界最大級のワンプラットフォーム「GREE Platform」をグローバルに展開しています。

          現在、「GREE Platform」にて北米・欧州に配信中で、この秋日本でも提供が開始されるアクションバトルRPG「MONPLA SMASH（モンプラスマッシュ）」はNode.jsを利用しており、世界規模での導入に取り組んでいます。

# シルバースポンサー
#=========================

  - 
    label: Silver Sponsors
    label_ja: シルバースポンサー
    icon: ico_03.png
    companies:
      - 
        name: Joyent
        url: http://www.joyent.com
        img: joyent.png
        description: |-
          Joyent は今日の Web やモバイル向けアプリケーションがに求められる高度な要求に特化した、IaaS を提供するハイポフォーマンスなクラウドインフラストラクチャの企業です。
          また Node.js をの開発を強く牽引する企業でもあり、サーバサイド JavaScript の開発環境を広く扱っています。

          興味のある方は[http://www.joyent.com](http://www.joyent.com)も是非御覧ください。

      - 
        name: Noejitsu
        url: http://nodejitsu.com/
        img: nodejitsu.png
        description: |-
            NodejitsuはNode.jsの開発者に、多くの最適なツールやサービスを提供します。Nodejitsuが提供するシンプルで信頼性の高いNode.jsのホスティングサービスは、エンタープライズ用途にもライセンス可能で、自社のクラウドでホスティングすることもできます。 チームはオープンソースにも深く貢献しており、多くのプロジェクトにコントリビュートし、コミュニティでも広く活動しています。

      - 
        name: ニフティ
        url: http://cloud.nifty.com/
        img: nifty.png
        description: |-
          ニフティ株式会社は“ニフティとなら、きっとかなう。 With Us, You Can.”を経営理念とし、安心安全なインターネットサービス、高品質なクラウドサービスを提供しています。Node.jsにも取り組んでいます。
          
      - 
        name: PixelGrid
        url: http://www.pxgrid.com/
        img: pxgrid.png
        description: |-
          ピクセルグリッドはJavaScriptの会社です。Webアプリケーションのフロントエンド開発を得意としhtml5やCSS3といった技術を積極的に活用しています。node.jsの利用にも取り組んでいます。

# 後援企業
#=========================

  - 
    label: Supporters
    label_ja: 後援
    icon: ico_04.png
    companies:
      - 
        name: Node Ninja
        url: http://node-ninja.com/
        img: node-ninja.png
      - 
        name: 法政大学情報科学部
        url: http://cis.k.hosei.ac.jp/
        img: housei.png
        description: |-
          法政大学 情報科学部は、情報科学に関する最先端の専門的知識・技術の修得だけでなく、次から次へ新しい概念と技術を創造し、世界を舞台に情報化社会をリードしてゆく技術者・研究者を最新の教育環境のもとで育成していきます。
      - 
        name: SINAP
        url: http://sinap.jp/
        img: sinap.png

sessions:
  #LT:
  #  -
  #    name: スピーカー1
  #    title: タイトル1
  #    twitter: xxx
  #  -
  #    name: スピーカー2
  #    title: タイトル2
